sonar.projectKey=CloudGenius-OPIP
sonar.projectName=CloudGenius OPIP
sonar.sourceEncoding=UTF-8
sonar.sources=frontend,services/population-api
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/__pycache__/**,**/.venv/**,**/venv/**
